// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/conf/v1/bootstrap.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 引导信息
type Bootstrap struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Name          string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // 服务名
	Server        *Server                     `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`                                                                               // 服务配置
	Client        *Client                     `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`                                                                               // 客户端配置
	Data          *Data                       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // 数据配置
	Trace         *Tracer                     `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`                                                                                 // 链路追踪配置
	Logger        *Logger                     `protobuf:"bytes,6,opt,name=logger,proto3" json:"logger,omitempty"`                                                                               // 日志配置
	Registry      *Registry                   `protobuf:"bytes,7,opt,name=registry,proto3" json:"registry,omitempty"`                                                                           // 注册中心配置
	Business      map[string]*structpb.Struct `protobuf:"bytes,8,rep,name=business,proto3" json:"business,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 自定义业务配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_api_conf_v1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetTrace() *Tracer {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Bootstrap) GetLogger() *Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetBusiness() map[string]*structpb.Struct {
	if x != nil {
		return x.Business
	}
	return nil
}

var File_api_conf_v1_bootstrap_proto protoreflect.FileDescriptor

const file_api_conf_v1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/conf/v1/bootstrap.proto\x12\x04conf\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18api/conf/v1/client.proto\x1a\x16api/conf/v1/data.proto\x1a\x18api/conf/v1/logger.proto\x1a\x1aapi/conf/v1/registry.proto\x1a\x18api/conf/v1/server.proto\x1a\x18api/conf/v1/tracer.proto\"\x92\x03\n" +
	"\tBootstrap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x06server\x18\x02 \x01(\v2\f.conf.ServerR\x06server\x12$\n" +
	"\x06client\x18\x03 \x01(\v2\f.conf.ClientR\x06client\x12\x1e\n" +
	"\x04data\x18\x04 \x01(\v2\n" +
	".conf.DataR\x04data\x12\"\n" +
	"\x05trace\x18\x05 \x01(\v2\f.conf.TracerR\x05trace\x12$\n" +
	"\x06logger\x18\x06 \x01(\v2\f.conf.LoggerR\x06logger\x12*\n" +
	"\bregistry\x18\a \x01(\v2\x0e.conf.RegistryR\bregistry\x129\n" +
	"\bbusiness\x18\b \x03(\v2\x1d.conf.Bootstrap.BusinessEntryR\bbusiness\x1aT\n" +
	"\rBusinessEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01B\x86\x01\n" +
	"\bcom.confB\x0eBootstrapProtoP\x01Z:github.com/fzf-labs/kratos-contrib/api/conf/v1/api/conf/v1\xa2\x02\x03CXX\xaa\x02\x04Conf\xca\x02\x04Conf\xe2\x02\x10Conf\\GPBMetadata\xea\x02\x04Confb\x06proto3"

var (
	file_api_conf_v1_bootstrap_proto_rawDescOnce sync.Once
	file_api_conf_v1_bootstrap_proto_rawDescData []byte
)

func file_api_conf_v1_bootstrap_proto_rawDescGZIP() []byte {
	file_api_conf_v1_bootstrap_proto_rawDescOnce.Do(func() {
		file_api_conf_v1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conf_v1_bootstrap_proto_rawDesc), len(file_api_conf_v1_bootstrap_proto_rawDesc)))
	})
	return file_api_conf_v1_bootstrap_proto_rawDescData
}

var file_api_conf_v1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_conf_v1_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),       // 0: conf.Bootstrap
	nil,                     // 1: conf.Bootstrap.BusinessEntry
	(*Server)(nil),          // 2: conf.Server
	(*Client)(nil),          // 3: conf.Client
	(*Data)(nil),            // 4: conf.Data
	(*Tracer)(nil),          // 5: conf.Tracer
	(*Logger)(nil),          // 6: conf.Logger
	(*Registry)(nil),        // 7: conf.Registry
	(*structpb.Struct)(nil), // 8: google.protobuf.Struct
}
var file_api_conf_v1_bootstrap_proto_depIdxs = []int32{
	2, // 0: conf.Bootstrap.server:type_name -> conf.Server
	3, // 1: conf.Bootstrap.client:type_name -> conf.Client
	4, // 2: conf.Bootstrap.data:type_name -> conf.Data
	5, // 3: conf.Bootstrap.trace:type_name -> conf.Tracer
	6, // 4: conf.Bootstrap.logger:type_name -> conf.Logger
	7, // 5: conf.Bootstrap.registry:type_name -> conf.Registry
	1, // 6: conf.Bootstrap.business:type_name -> conf.Bootstrap.BusinessEntry
	8, // 7: conf.Bootstrap.BusinessEntry.value:type_name -> google.protobuf.Struct
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_conf_v1_bootstrap_proto_init() }
func file_api_conf_v1_bootstrap_proto_init() {
	if File_api_conf_v1_bootstrap_proto != nil {
		return
	}
	file_api_conf_v1_client_proto_init()
	file_api_conf_v1_data_proto_init()
	file_api_conf_v1_logger_proto_init()
	file_api_conf_v1_registry_proto_init()
	file_api_conf_v1_server_proto_init()
	file_api_conf_v1_tracer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conf_v1_bootstrap_proto_rawDesc), len(file_api_conf_v1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_conf_v1_bootstrap_proto_goTypes,
		DependencyIndexes: file_api_conf_v1_bootstrap_proto_depIdxs,
		MessageInfos:      file_api_conf_v1_bootstrap_proto_msgTypes,
	}.Build()
	File_api_conf_v1_bootstrap_proto = out.File
	file_api_conf_v1_bootstrap_proto_goTypes = nil
	file_api_conf_v1_bootstrap_proto_depIdxs = nil
}
