// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/conf/v1/business.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 业务
type Business struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           *Business_Jwt          `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"` // JWT 配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Business) Reset() {
	*x = Business{}
	mi := &file_api_conf_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Business) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business) ProtoMessage() {}

func (x *Business) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business.ProtoReflect.Descriptor instead.
func (*Business) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *Business) GetJwt() *Business_Jwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

// JWT校验
type Business_Jwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessSecret  string                 `protobuf:"bytes,1,opt,name=accessSecret,proto3" json:"accessSecret,omitempty"`  // JWT 秘钥
	RefreshAfter  int32                  `protobuf:"varint,2,opt,name=refreshAfter,proto3" json:"refreshAfter,omitempty"` // 刷新时间
	AccessExpire  int32                  `protobuf:"varint,3,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"` // 访问过期时间
	Issuer        string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`              // 签发者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Business_Jwt) Reset() {
	*x = Business_Jwt{}
	mi := &file_api_conf_v1_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Business_Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business_Jwt) ProtoMessage() {}

func (x *Business_Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business_Jwt.ProtoReflect.Descriptor instead.
func (*Business_Jwt) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_business_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Business_Jwt) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *Business_Jwt) GetRefreshAfter() int32 {
	if x != nil {
		return x.RefreshAfter
	}
	return 0
}

func (x *Business_Jwt) GetAccessExpire() int32 {
	if x != nil {
		return x.AccessExpire
	}
	return 0
}

func (x *Business_Jwt) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

var File_api_conf_v1_business_proto protoreflect.FileDescriptor

const file_api_conf_v1_business_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/conf/v1/business.proto\x12\x04conf\"\xbc\x01\n" +
	"\bBusiness\x12$\n" +
	"\x03jwt\x18\x01 \x01(\v2\x12.conf.Business.JwtR\x03jwt\x1a\x89\x01\n" +
	"\x03Jwt\x12\"\n" +
	"\faccessSecret\x18\x01 \x01(\tR\faccessSecret\x12\"\n" +
	"\frefreshAfter\x18\x02 \x01(\x05R\frefreshAfter\x12\"\n" +
	"\faccessExpire\x18\x03 \x01(\x05R\faccessExpire\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuerB\x85\x01\n" +
	"\bcom.confB\rBusinessProtoP\x01Z:github.com/fzf-labs/kratos-contrib/api/conf/v1/api/conf/v1\xa2\x02\x03CXX\xaa\x02\x04Conf\xca\x02\x04Conf\xe2\x02\x10Conf\\GPBMetadata\xea\x02\x04Confb\x06proto3"

var (
	file_api_conf_v1_business_proto_rawDescOnce sync.Once
	file_api_conf_v1_business_proto_rawDescData []byte
)

func file_api_conf_v1_business_proto_rawDescGZIP() []byte {
	file_api_conf_v1_business_proto_rawDescOnce.Do(func() {
		file_api_conf_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conf_v1_business_proto_rawDesc), len(file_api_conf_v1_business_proto_rawDesc)))
	})
	return file_api_conf_v1_business_proto_rawDescData
}

var file_api_conf_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_conf_v1_business_proto_goTypes = []any{
	(*Business)(nil),     // 0: conf.Business
	(*Business_Jwt)(nil), // 1: conf.Business.Jwt
}
var file_api_conf_v1_business_proto_depIdxs = []int32{
	1, // 0: conf.Business.jwt:type_name -> conf.Business.Jwt
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_conf_v1_business_proto_init() }
func file_api_conf_v1_business_proto_init() {
	if File_api_conf_v1_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conf_v1_business_proto_rawDesc), len(file_api_conf_v1_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_conf_v1_business_proto_goTypes,
		DependencyIndexes: file_api_conf_v1_business_proto_depIdxs,
		MessageInfos:      file_api_conf_v1_business_proto_msgTypes,
	}.Build()
	File_api_conf_v1_business_proto = out.File
	file_api_conf_v1_business_proto_goTypes = nil
	file_api_conf_v1_business_proto_depIdxs = nil
}
