// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/conf/v1/data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gorm          *Data_Gorm             `protobuf:"bytes,1,opt,name=gorm,proto3" json:"gorm,omitempty"`   // 数据库 gorm
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"` // Redis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_api_conf_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetGorm() *Data_Gorm {
	if x != nil {
		return x.Gorm
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

// 数据库 gorm
type Data_Gorm struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DataSourceName  string                 `protobuf:"bytes,1,opt,name=dataSourceName,proto3" json:"dataSourceName,omitempty"`   // DSN
	MaxIdleConn     int32                  `protobuf:"varint,2,opt,name=maxIdleConn,proto3" json:"maxIdleConn,omitempty"`        // 闲置连接数
	MaxOpenConn     int32                  `protobuf:"varint,3,opt,name=maxOpenConn,proto3" json:"maxOpenConn,omitempty"`        // 最大打开的连接数
	ConnMaxLifeTime *durationpb.Duration   `protobuf:"bytes,4,opt,name=connMaxLifeTime,proto3" json:"connMaxLifeTime,omitempty"` // 连接可以重复使用的最长时间
	ShowLog         bool                   `protobuf:"varint,5,opt,name=showLog,proto3" json:"showLog,omitempty"`                // 慢日志开关
	Tracing         bool                   `protobuf:"varint,6,opt,name=tracing,proto3" json:"tracing,omitempty"`                // 链路追踪开关
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Gorm) Reset() {
	*x = Data_Gorm{}
	mi := &file_api_conf_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Gorm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Gorm) ProtoMessage() {}

func (x *Data_Gorm) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Gorm.ProtoReflect.Descriptor instead.
func (*Data_Gorm) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Data_Gorm) GetDataSourceName() string {
	if x != nil {
		return x.DataSourceName
	}
	return ""
}

func (x *Data_Gorm) GetMaxIdleConn() int32 {
	if x != nil {
		return x.MaxIdleConn
	}
	return 0
}

func (x *Data_Gorm) GetMaxOpenConn() int32 {
	if x != nil {
		return x.MaxOpenConn
	}
	return 0
}

func (x *Data_Gorm) GetConnMaxLifeTime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifeTime
	}
	return nil
}

func (x *Data_Gorm) GetShowLog() bool {
	if x != nil {
		return x.ShowLog
	}
	return false
}

func (x *Data_Gorm) GetTracing() bool {
	if x != nil {
		return x.Tracing
	}
	return false
}

// redis
type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`           // 网络
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                 // 服务端地址
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`         // 账号
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`         // 密码
	Db            int32                  `protobuf:"varint,5,opt,name=db,proto3" json:"db,omitempty"`                    // 数据库索引
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,6,opt,name=dialTimeout,proto3" json:"dialTimeout,omitempty"`   // 连接超时时间
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,7,opt,name=readTimeout,proto3" json:"readTimeout,omitempty"`   // 读取超时时间
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,8,opt,name=writeTimeout,proto3" json:"writeTimeout,omitempty"` // 写入超时时间
	Tracing       bool                   `protobuf:"varint,9,opt,name=tracing,proto3" json:"tracing,omitempty"`          // 链路追踪开关
	Metrics       bool                   `protobuf:"varint,10,opt,name=metrics,proto3" json:"metrics,omitempty"`         // 指标开关
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_api_conf_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_data_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetTracing() bool {
	if x != nil {
		return x.Tracing
	}
	return false
}

func (x *Data_Redis) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

var File_api_conf_v1_data_proto protoreflect.FileDescriptor

const file_api_conf_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x16api/conf/v1/data.proto\x12\x04conf\x1a\x1egoogle/protobuf/duration.proto\"\xae\x05\n" +
	"\x04Data\x12#\n" +
	"\x04gorm\x18\x01 \x01(\v2\x0f.conf.Data.GormR\x04gorm\x12&\n" +
	"\x05redis\x18\x02 \x01(\v2\x10.conf.Data.RedisR\x05redis\x1a\xeb\x01\n" +
	"\x04Gorm\x12&\n" +
	"\x0edataSourceName\x18\x01 \x01(\tR\x0edataSourceName\x12 \n" +
	"\vmaxIdleConn\x18\x02 \x01(\x05R\vmaxIdleConn\x12 \n" +
	"\vmaxOpenConn\x18\x03 \x01(\x05R\vmaxOpenConn\x12C\n" +
	"\x0fconnMaxLifeTime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifeTime\x12\x18\n" +
	"\ashowLog\x18\x05 \x01(\bR\ashowLog\x12\x18\n" +
	"\atracing\x18\x06 \x01(\bR\atracing\x1a\xea\x02\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x05 \x01(\x05R\x02db\x12;\n" +
	"\vdialTimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12;\n" +
	"\vreadTimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12=\n" +
	"\fwriteTimeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x18\n" +
	"\atracing\x18\t \x01(\bR\atracing\x12\x18\n" +
	"\ametrics\x18\n" +
	" \x01(\bR\ametricsB\x81\x01\n" +
	"\bcom.confB\tDataProtoP\x01Z:github.com/fzf-labs/kratos-contrib/api/conf/v1/api/conf/v1\xa2\x02\x03CXX\xaa\x02\x04Conf\xca\x02\x04Conf\xe2\x02\x10Conf\\GPBMetadata\xea\x02\x04Confb\x06proto3"

var (
	file_api_conf_v1_data_proto_rawDescOnce sync.Once
	file_api_conf_v1_data_proto_rawDescData []byte
)

func file_api_conf_v1_data_proto_rawDescGZIP() []byte {
	file_api_conf_v1_data_proto_rawDescOnce.Do(func() {
		file_api_conf_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conf_v1_data_proto_rawDesc), len(file_api_conf_v1_data_proto_rawDesc)))
	})
	return file_api_conf_v1_data_proto_rawDescData
}

var file_api_conf_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_conf_v1_data_proto_goTypes = []any{
	(*Data)(nil),                // 0: conf.Data
	(*Data_Gorm)(nil),           // 1: conf.Data.Gorm
	(*Data_Redis)(nil),          // 2: conf.Data.Redis
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_api_conf_v1_data_proto_depIdxs = []int32{
	1, // 0: conf.Data.gorm:type_name -> conf.Data.Gorm
	2, // 1: conf.Data.redis:type_name -> conf.Data.Redis
	3, // 2: conf.Data.Gorm.connMaxLifeTime:type_name -> google.protobuf.Duration
	3, // 3: conf.Data.Redis.dialTimeout:type_name -> google.protobuf.Duration
	3, // 4: conf.Data.Redis.readTimeout:type_name -> google.protobuf.Duration
	3, // 5: conf.Data.Redis.writeTimeout:type_name -> google.protobuf.Duration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_conf_v1_data_proto_init() }
func file_api_conf_v1_data_proto_init() {
	if File_api_conf_v1_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conf_v1_data_proto_rawDesc), len(file_api_conf_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_conf_v1_data_proto_goTypes,
		DependencyIndexes: file_api_conf_v1_data_proto_depIdxs,
		MessageInfos:      file_api_conf_v1_data_proto_msgTypes,
	}.Build()
	File_api_conf_v1_data_proto = out.File
	file_api_conf_v1_data_proto_goTypes = nil
	file_api_conf_v1_data_proto_depIdxs = nil
}
