// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/conf/v1/middleware.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Middleware struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnableLogging        bool                   `protobuf:"varint,1,opt,name=enableLogging,proto3" json:"enableLogging,omitempty"`               // 日志开关
	EnableRecovery       bool                   `protobuf:"varint,2,opt,name=enableRecovery,proto3" json:"enableRecovery,omitempty"`             // 异常恢复
	EnableTracing        bool                   `protobuf:"varint,3,opt,name=enableTracing,proto3" json:"enableTracing,omitempty"`               // 链路追踪开关
	EnableMetadata       bool                   `protobuf:"varint,4,opt,name=enableMetadata,proto3" json:"enableMetadata,omitempty"`             // 链路追踪开关
	EnableValidate       bool                   `protobuf:"varint,5,opt,name=enableValidate,proto3" json:"enableValidate,omitempty"`             // 参数校验开关
	EnableCircuitBreaker bool                   `protobuf:"varint,6,opt,name=enableCircuitBreaker,proto3" json:"enableCircuitBreaker,omitempty"` // 熔断器
	EnableRateLimiter    bool                   `protobuf:"varint,7,opt,name=enableRateLimiter,proto3" json:"enableRateLimiter,omitempty"`       // 限流器
	EnableMetrics        bool                   `protobuf:"varint,8,opt,name=enableMetrics,proto3" json:"enableMetrics,omitempty"`               // 性能指标
	Limiter              *RateLimiter           `protobuf:"bytes,9,opt,name=limiter,proto3" json:"limiter,omitempty"`                            // 限流器配置
	Metrics              *Metrics               `protobuf:"bytes,10,opt,name=metrics,proto3" json:"metrics,omitempty"`                           // 性能指标配置
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Middleware) Reset() {
	*x = Middleware{}
	mi := &file_api_conf_v1_middleware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middleware) ProtoMessage() {}

func (x *Middleware) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_middleware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Middleware.ProtoReflect.Descriptor instead.
func (*Middleware) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *Middleware) GetEnableLogging() bool {
	if x != nil {
		return x.EnableLogging
	}
	return false
}

func (x *Middleware) GetEnableRecovery() bool {
	if x != nil {
		return x.EnableRecovery
	}
	return false
}

func (x *Middleware) GetEnableTracing() bool {
	if x != nil {
		return x.EnableTracing
	}
	return false
}

func (x *Middleware) GetEnableMetadata() bool {
	if x != nil {
		return x.EnableMetadata
	}
	return false
}

func (x *Middleware) GetEnableValidate() bool {
	if x != nil {
		return x.EnableValidate
	}
	return false
}

func (x *Middleware) GetEnableCircuitBreaker() bool {
	if x != nil {
		return x.EnableCircuitBreaker
	}
	return false
}

func (x *Middleware) GetEnableRateLimiter() bool {
	if x != nil {
		return x.EnableRateLimiter
	}
	return false
}

func (x *Middleware) GetEnableMetrics() bool {
	if x != nil {
		return x.EnableMetrics
	}
	return false
}

func (x *Middleware) GetLimiter() *RateLimiter {
	if x != nil {
		return x.Limiter
	}
	return nil
}

func (x *Middleware) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 限流器
type RateLimiter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        *durationpb.Duration   `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`              // 窗口时间
	Bucket        int64                  `protobuf:"varint,2,opt,name=bucket,proto3" json:"bucket,omitempty"`             // 桶大小
	CpuThreshold  int64                  `protobuf:"varint,3,opt,name=cpuThreshold,proto3" json:"cpuThreshold,omitempty"` // CPU阈值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimiter) Reset() {
	*x = RateLimiter{}
	mi := &file_api_conf_v1_middleware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimiter) ProtoMessage() {}

func (x *RateLimiter) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_middleware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimiter.ProtoReflect.Descriptor instead.
func (*RateLimiter) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimiter) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *RateLimiter) GetBucket() int64 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

func (x *RateLimiter) GetCpuThreshold() int64 {
	if x != nil {
		return x.CpuThreshold
	}
	return 0
}

// 性能指标
type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Histogram     bool                   `protobuf:"varint,1,opt,name=histogram,proto3" json:"histogram,omitempty"` // 直方图
	Counter       bool                   `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`     // 计数器
	Gauge         bool                   `protobuf:"varint,3,opt,name=gauge,proto3" json:"gauge,omitempty"`         // 仪表盘
	Summary       bool                   `protobuf:"varint,4,opt,name=summary,proto3" json:"summary,omitempty"`     // 摘要
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_api_conf_v1_middleware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_middleware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_middleware_proto_rawDescGZIP(), []int{2}
}

func (x *Metrics) GetHistogram() bool {
	if x != nil {
		return x.Histogram
	}
	return false
}

func (x *Metrics) GetCounter() bool {
	if x != nil {
		return x.Counter
	}
	return false
}

func (x *Metrics) GetGauge() bool {
	if x != nil {
		return x.Gauge
	}
	return false
}

func (x *Metrics) GetSummary() bool {
	if x != nil {
		return x.Summary
	}
	return false
}

var File_api_conf_v1_middleware_proto protoreflect.FileDescriptor

const file_api_conf_v1_middleware_proto_rawDesc = "" +
	"\n" +
	"\x1capi/conf/v1/middleware.proto\x12\x04conf\x1a\x1egoogle/protobuf/duration.proto\"\xae\x03\n" +
	"\n" +
	"Middleware\x12$\n" +
	"\renableLogging\x18\x01 \x01(\bR\renableLogging\x12&\n" +
	"\x0eenableRecovery\x18\x02 \x01(\bR\x0eenableRecovery\x12$\n" +
	"\renableTracing\x18\x03 \x01(\bR\renableTracing\x12&\n" +
	"\x0eenableMetadata\x18\x04 \x01(\bR\x0eenableMetadata\x12&\n" +
	"\x0eenableValidate\x18\x05 \x01(\bR\x0eenableValidate\x122\n" +
	"\x14enableCircuitBreaker\x18\x06 \x01(\bR\x14enableCircuitBreaker\x12,\n" +
	"\x11enableRateLimiter\x18\a \x01(\bR\x11enableRateLimiter\x12$\n" +
	"\renableMetrics\x18\b \x01(\bR\renableMetrics\x12+\n" +
	"\alimiter\x18\t \x01(\v2\x11.conf.RateLimiterR\alimiter\x12'\n" +
	"\ametrics\x18\n" +
	" \x01(\v2\r.conf.MetricsR\ametrics\"|\n" +
	"\vRateLimiter\x121\n" +
	"\x06window\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\x03R\x06bucket\x12\"\n" +
	"\fcpuThreshold\x18\x03 \x01(\x03R\fcpuThreshold\"q\n" +
	"\aMetrics\x12\x1c\n" +
	"\thistogram\x18\x01 \x01(\bR\thistogram\x12\x18\n" +
	"\acounter\x18\x02 \x01(\bR\acounter\x12\x14\n" +
	"\x05gauge\x18\x03 \x01(\bR\x05gauge\x12\x18\n" +
	"\asummary\x18\x04 \x01(\bR\asummaryB\x87\x01\n" +
	"\bcom.confB\x0fMiddlewareProtoP\x01Z:github.com/fzf-labs/kratos-contrib/api/conf/v1/api/conf/v1\xa2\x02\x03CXX\xaa\x02\x04Conf\xca\x02\x04Conf\xe2\x02\x10Conf\\GPBMetadata\xea\x02\x04Confb\x06proto3"

var (
	file_api_conf_v1_middleware_proto_rawDescOnce sync.Once
	file_api_conf_v1_middleware_proto_rawDescData []byte
)

func file_api_conf_v1_middleware_proto_rawDescGZIP() []byte {
	file_api_conf_v1_middleware_proto_rawDescOnce.Do(func() {
		file_api_conf_v1_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conf_v1_middleware_proto_rawDesc), len(file_api_conf_v1_middleware_proto_rawDesc)))
	})
	return file_api_conf_v1_middleware_proto_rawDescData
}

var file_api_conf_v1_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_conf_v1_middleware_proto_goTypes = []any{
	(*Middleware)(nil),          // 0: conf.Middleware
	(*RateLimiter)(nil),         // 1: conf.RateLimiter
	(*Metrics)(nil),             // 2: conf.Metrics
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_api_conf_v1_middleware_proto_depIdxs = []int32{
	1, // 0: conf.Middleware.limiter:type_name -> conf.RateLimiter
	2, // 1: conf.Middleware.metrics:type_name -> conf.Metrics
	3, // 2: conf.RateLimiter.window:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_conf_v1_middleware_proto_init() }
func file_api_conf_v1_middleware_proto_init() {
	if File_api_conf_v1_middleware_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conf_v1_middleware_proto_rawDesc), len(file_api_conf_v1_middleware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_conf_v1_middleware_proto_goTypes,
		DependencyIndexes: file_api_conf_v1_middleware_proto_depIdxs,
		MessageInfos:      file_api_conf_v1_middleware_proto_msgTypes,
	}.Build()
	File_api_conf_v1_middleware_proto = out.File
	file_api_conf_v1_middleware_proto_goTypes = nil
	file_api_conf_v1_middleware_proto_depIdxs = nil
}
