// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/conf/v1/registry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册发现中心
type Registry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes
	Type          string           `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`     // 类型 none，consul，etcd，nacos
	Consul        *Registry_Consul `protobuf:"bytes,2,opt,name=consul,proto3" json:"consul,omitempty"` // Consul
	Etcd          *Registry_Etcd   `protobuf:"bytes,3,opt,name=etcd,proto3" json:"etcd,omitempty"`     // Etcd
	Nacos         *Registry_Nacos  `protobuf:"bytes,4,opt,name=nacos,proto3" json:"nacos,omitempty"`   // Nacos
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_api_conf_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Registry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Registry) GetConsul() *Registry_Consul {
	if x != nil {
		return x.Consul
	}
	return nil
}

func (x *Registry) GetEtcd() *Registry_Etcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

func (x *Registry) GetNacos() *Registry_Nacos {
	if x != nil {
		return x.Nacos
	}
	return nil
}

// Consul
type Registry_Consul struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`            // 网络样式
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`          // 服务端地址
	HealthCheck   bool                   `protobuf:"varint,3,opt,name=healthCheck,proto3" json:"healthCheck,omitempty"` // 健康检查
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry_Consul) Reset() {
	*x = Registry_Consul{}
	mi := &file_api_conf_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry_Consul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry_Consul) ProtoMessage() {}

func (x *Registry_Consul) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry_Consul.ProtoReflect.Descriptor instead.
func (*Registry_Consul) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_registry_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Registry_Consul) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Registry_Consul) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Registry_Consul) GetHealthCheck() bool {
	if x != nil {
		return x.HealthCheck
	}
	return false
}

// Etcd
type Registry_Etcd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // 端点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry_Etcd) Reset() {
	*x = Registry_Etcd{}
	mi := &file_api_conf_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry_Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry_Etcd) ProtoMessage() {}

func (x *Registry_Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry_Etcd.ProtoReflect.Descriptor instead.
func (*Registry_Etcd) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_registry_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Registry_Etcd) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// Nacos
type Registry_Nacos struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Address              string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                             // 服务端地址
	Port                 uint64                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                                  // 服务端端口
	NamespaceId          string                 `protobuf:"bytes,3,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`                     // 命名空间ID
	LogLevel             string                 `protobuf:"bytes,4,opt,name=logLevel,proto3" json:"logLevel,omitempty"`                           // 日志等级
	CacheDir             string                 `protobuf:"bytes,5,opt,name=cacheDir,proto3" json:"cacheDir,omitempty"`                           // 缓存目录
	LogDir               string                 `protobuf:"bytes,6,opt,name=logDir,proto3" json:"logDir,omitempty"`                               // 日志目录
	UpdateThreadNum      int32                  `protobuf:"varint,7,opt,name=updateThreadNum,proto3" json:"updateThreadNum,omitempty"`            // 更新服务的线程数
	Timeout              *durationpb.Duration   `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`                             // http请求超时时间，单位: 毫秒
	BeatInterval         *durationpb.Duration   `protobuf:"bytes,9,opt,name=beatInterval,proto3" json:"beatInterval,omitempty"`                   // 心跳间隔时间，单位: 毫秒
	NotLoadCacheAtStart  bool                   `protobuf:"varint,10,opt,name=notLoadCacheAtStart,proto3" json:"notLoadCacheAtStart,omitempty"`   // 在启动时不读取本地缓存数据，true: 不读取，false: 读取
	UpdateCacheWhenEmpty bool                   `protobuf:"varint,11,opt,name=updateCacheWhenEmpty,proto3" json:"updateCacheWhenEmpty,omitempty"` // 当服务列表为空时是否更新本地缓存，true: 更新,false: 不更新
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Registry_Nacos) Reset() {
	*x = Registry_Nacos{}
	mi := &file_api_conf_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry_Nacos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry_Nacos) ProtoMessage() {}

func (x *Registry_Nacos) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry_Nacos.ProtoReflect.Descriptor instead.
func (*Registry_Nacos) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_registry_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Registry_Nacos) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Registry_Nacos) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Registry_Nacos) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Registry_Nacos) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Registry_Nacos) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *Registry_Nacos) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Registry_Nacos) GetUpdateThreadNum() int32 {
	if x != nil {
		return x.UpdateThreadNum
	}
	return 0
}

func (x *Registry_Nacos) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Registry_Nacos) GetBeatInterval() *durationpb.Duration {
	if x != nil {
		return x.BeatInterval
	}
	return nil
}

func (x *Registry_Nacos) GetNotLoadCacheAtStart() bool {
	if x != nil {
		return x.NotLoadCacheAtStart
	}
	return false
}

func (x *Registry_Nacos) GetUpdateCacheWhenEmpty() bool {
	if x != nil {
		return x.UpdateCacheWhenEmpty
	}
	return false
}

var File_api_conf_v1_registry_proto protoreflect.FileDescriptor

const file_api_conf_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/conf/v1/registry.proto\x12\x04conf\x1a\x1egoogle/protobuf/duration.proto\"\xd4\x05\n" +
	"\bRegistry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\x06consul\x18\x02 \x01(\v2\x15.conf.Registry.ConsulR\x06consul\x12'\n" +
	"\x04etcd\x18\x03 \x01(\v2\x13.conf.Registry.EtcdR\x04etcd\x12*\n" +
	"\x05nacos\x18\x04 \x01(\v2\x14.conf.Registry.NacosR\x05nacos\x1a\\\n" +
	"\x06Consul\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12 \n" +
	"\vhealthCheck\x18\x03 \x01(\bR\vhealthCheck\x1a$\n" +
	"\x04Etcd\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x1a\xab\x03\n" +
	"\x05Nacos\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x04R\x04port\x12 \n" +
	"\vnamespaceId\x18\x03 \x01(\tR\vnamespaceId\x12\x1a\n" +
	"\blogLevel\x18\x04 \x01(\tR\blogLevel\x12\x1a\n" +
	"\bcacheDir\x18\x05 \x01(\tR\bcacheDir\x12\x16\n" +
	"\x06logDir\x18\x06 \x01(\tR\x06logDir\x12(\n" +
	"\x0fupdateThreadNum\x18\a \x01(\x05R\x0fupdateThreadNum\x123\n" +
	"\atimeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12=\n" +
	"\fbeatInterval\x18\t \x01(\v2\x19.google.protobuf.DurationR\fbeatInterval\x120\n" +
	"\x13notLoadCacheAtStart\x18\n" +
	" \x01(\bR\x13notLoadCacheAtStart\x122\n" +
	"\x14updateCacheWhenEmpty\x18\v \x01(\bR\x14updateCacheWhenEmptyB\x85\x01\n" +
	"\bcom.confB\rRegistryProtoP\x01Z:github.com/fzf-labs/kratos-contrib/api/conf/v1/api/conf/v1\xa2\x02\x03CXX\xaa\x02\x04Conf\xca\x02\x04Conf\xe2\x02\x10Conf\\GPBMetadata\xea\x02\x04Confb\x06proto3"

var (
	file_api_conf_v1_registry_proto_rawDescOnce sync.Once
	file_api_conf_v1_registry_proto_rawDescData []byte
)

func file_api_conf_v1_registry_proto_rawDescGZIP() []byte {
	file_api_conf_v1_registry_proto_rawDescOnce.Do(func() {
		file_api_conf_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conf_v1_registry_proto_rawDesc), len(file_api_conf_v1_registry_proto_rawDesc)))
	})
	return file_api_conf_v1_registry_proto_rawDescData
}

var file_api_conf_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_conf_v1_registry_proto_goTypes = []any{
	(*Registry)(nil),            // 0: conf.Registry
	(*Registry_Consul)(nil),     // 1: conf.Registry.Consul
	(*Registry_Etcd)(nil),       // 2: conf.Registry.Etcd
	(*Registry_Nacos)(nil),      // 3: conf.Registry.Nacos
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_api_conf_v1_registry_proto_depIdxs = []int32{
	1, // 0: conf.Registry.consul:type_name -> conf.Registry.Consul
	2, // 1: conf.Registry.etcd:type_name -> conf.Registry.Etcd
	3, // 2: conf.Registry.nacos:type_name -> conf.Registry.Nacos
	4, // 3: conf.Registry.Nacos.timeout:type_name -> google.protobuf.Duration
	4, // 4: conf.Registry.Nacos.beatInterval:type_name -> google.protobuf.Duration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_conf_v1_registry_proto_init() }
func file_api_conf_v1_registry_proto_init() {
	if File_api_conf_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conf_v1_registry_proto_rawDesc), len(file_api_conf_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_conf_v1_registry_proto_goTypes,
		DependencyIndexes: file_api_conf_v1_registry_proto_depIdxs,
		MessageInfos:      file_api_conf_v1_registry_proto_msgTypes,
	}.Build()
	File_api_conf_v1_registry_proto = out.File
	file_api_conf_v1_registry_proto_goTypes = nil
	file_api_conf_v1_registry_proto_depIdxs = nil
}
