// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/conf/v1/server.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"` // HTTP服务
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"` // gRPC服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_api_conf_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

// HTTP
type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`          // 网络
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                // 服务监听地址
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`          // 超时时间
	Middleware    *Middleware            `protobuf:"bytes,4,opt,name=middleware,proto3" json:"middleware,omitempty"`    // 中间件
	Cors          *Server_HTTP_CORS      `protobuf:"bytes,5,opt,name=cors,proto3" json:"cors,omitempty"`                // 跨域配置
	EnableCors    bool                   `protobuf:"varint,6,opt,name=enableCors,proto3" json:"enableCors,omitempty"`   // 启用跨域
	EnablePprof   bool                   `protobuf:"varint,7,opt,name=enablePprof,proto3" json:"enablePprof,omitempty"` // 启用pprof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_api_conf_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_HTTP) GetMiddleware() *Middleware {
	if x != nil {
		return x.Middleware
	}
	return nil
}

func (x *Server_HTTP) GetCors() *Server_HTTP_CORS {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *Server_HTTP) GetEnableCors() bool {
	if x != nil {
		return x.EnableCors
	}
	return false
}

func (x *Server_HTTP) GetEnablePprof() bool {
	if x != nil {
		return x.EnablePprof
	}
	return false
}

// gPRC
type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`       // 网络
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`             // 服务监听地址
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`       // 超时时间
	Middleware    *Middleware            `protobuf:"bytes,4,opt,name=middleware,proto3" json:"middleware,omitempty"` // 中间件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_api_conf_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_server_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_GRPC) GetMiddleware() *Middleware {
	if x != nil {
		return x.Middleware
	}
	return nil
}

type Server_HTTP_CORS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []string               `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"` // 允许的请求头
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"` // 允许的请求方法
	Origins       []string               `protobuf:"bytes,3,rep,name=origins,proto3" json:"origins,omitempty"` // 允许的请求源
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP_CORS) Reset() {
	*x = Server_HTTP_CORS{}
	mi := &file_api_conf_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP_CORS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP_CORS) ProtoMessage() {}

func (x *Server_HTTP_CORS) ProtoReflect() protoreflect.Message {
	mi := &file_api_conf_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP_CORS.ProtoReflect.Descriptor instead.
func (*Server_HTTP_CORS) Descriptor() ([]byte, []int) {
	return file_api_conf_v1_server_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Server_HTTP_CORS) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Server_HTTP_CORS) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Server_HTTP_CORS) GetOrigins() []string {
	if x != nil {
		return x.Origins
	}
	return nil
}

var File_api_conf_v1_server_proto protoreflect.FileDescriptor

const file_api_conf_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x18api/conf/v1/server.proto\x12\x04conf\x1a\x1capi/conf/v1/middleware.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd6\x04\n" +
	"\x06Server\x12%\n" +
	"\x04http\x18\x01 \x01(\v2\x11.conf.Server.HTTPR\x04http\x12%\n" +
	"\x04grpc\x18\x02 \x01(\v2\x11.conf.Server.GRPCR\x04grpc\x1a\xdf\x02\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x120\n" +
	"\n" +
	"middleware\x18\x04 \x01(\v2\x10.conf.MiddlewareR\n" +
	"middleware\x12*\n" +
	"\x04cors\x18\x05 \x01(\v2\x16.conf.Server.HTTP.CORSR\x04cors\x12\x1e\n" +
	"\n" +
	"enableCors\x18\x06 \x01(\bR\n" +
	"enableCors\x12 \n" +
	"\venablePprof\x18\a \x01(\bR\venablePprof\x1aT\n" +
	"\x04CORS\x12\x18\n" +
	"\aheaders\x18\x01 \x03(\tR\aheaders\x12\x18\n" +
	"\amethods\x18\x02 \x03(\tR\amethods\x12\x18\n" +
	"\aorigins\x18\x03 \x03(\tR\aorigins\x1a\x9b\x01\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x120\n" +
	"\n" +
	"middleware\x18\x04 \x01(\v2\x10.conf.MiddlewareR\n" +
	"middlewareB\x83\x01\n" +
	"\bcom.confB\vServerProtoP\x01Z:github.com/fzf-labs/kratos-contrib/api/conf/v1/api/conf/v1\xa2\x02\x03CXX\xaa\x02\x04Conf\xca\x02\x04Conf\xe2\x02\x10Conf\\GPBMetadata\xea\x02\x04Confb\x06proto3"

var (
	file_api_conf_v1_server_proto_rawDescOnce sync.Once
	file_api_conf_v1_server_proto_rawDescData []byte
)

func file_api_conf_v1_server_proto_rawDescGZIP() []byte {
	file_api_conf_v1_server_proto_rawDescOnce.Do(func() {
		file_api_conf_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conf_v1_server_proto_rawDesc), len(file_api_conf_v1_server_proto_rawDesc)))
	})
	return file_api_conf_v1_server_proto_rawDescData
}

var file_api_conf_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_conf_v1_server_proto_goTypes = []any{
	(*Server)(nil),              // 0: conf.Server
	(*Server_HTTP)(nil),         // 1: conf.Server.HTTP
	(*Server_GRPC)(nil),         // 2: conf.Server.GRPC
	(*Server_HTTP_CORS)(nil),    // 3: conf.Server.HTTP.CORS
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
	(*Middleware)(nil),          // 5: conf.Middleware
}
var file_api_conf_v1_server_proto_depIdxs = []int32{
	1, // 0: conf.Server.http:type_name -> conf.Server.HTTP
	2, // 1: conf.Server.grpc:type_name -> conf.Server.GRPC
	4, // 2: conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	5, // 3: conf.Server.HTTP.middleware:type_name -> conf.Middleware
	3, // 4: conf.Server.HTTP.cors:type_name -> conf.Server.HTTP.CORS
	4, // 5: conf.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	5, // 6: conf.Server.GRPC.middleware:type_name -> conf.Middleware
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_conf_v1_server_proto_init() }
func file_api_conf_v1_server_proto_init() {
	if File_api_conf_v1_server_proto != nil {
		return
	}
	file_api_conf_v1_middleware_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conf_v1_server_proto_rawDesc), len(file_api_conf_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_conf_v1_server_proto_goTypes,
		DependencyIndexes: file_api_conf_v1_server_proto_depIdxs,
		MessageInfos:      file_api_conf_v1_server_proto_msgTypes,
	}.Build()
	File_api_conf_v1_server_proto = out.File
	file_api_conf_v1_server_proto_goTypes = nil
	file_api_conf_v1_server_proto_depIdxs = nil
}
