// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: paginator/v1/paginator.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 搜索参数
type SearchParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` //字段
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` //值
	Exp   string `protobuf:"bytes,3,opt,name=exp,proto3" json:"exp,omitempty"`     //操作
	Logic string `protobuf:"bytes,4,opt,name=logic,proto3" json:"logic,omitempty"` //逻辑关系
}

func (x *SearchParam) Reset() {
	*x = SearchParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginator_v1_paginator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchParam) ProtoMessage() {}

func (x *SearchParam) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_v1_paginator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchParam.ProtoReflect.Descriptor instead.
func (*SearchParam) Descriptor() ([]byte, []int) {
	return file_paginator_v1_paginator_proto_rawDescGZIP(), []int{0}
}

func (x *SearchParam) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchParam) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *SearchParam) GetLogic() string {
	if x != nil {
		return x.Logic
	}
	return ""
}

// 排序参数
type OrderParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` //字段
	Exp   string `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`     //表达式 ASC,DESC
}

func (x *OrderParam) Reset() {
	*x = OrderParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginator_v1_paginator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderParam) ProtoMessage() {}

func (x *OrderParam) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_v1_paginator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderParam.ProtoReflect.Descriptor instead.
func (*OrderParam) Descriptor() ([]byte, []int) {
	return file_paginator_v1_paginator_proto_rawDescGZIP(), []int{1}
}

func (x *OrderParam) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OrderParam) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

// 分页请求
type PaginatorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         // 页码
	PageSize int32          `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 页数
	Search   []*SearchParam `protobuf:"bytes,3,rep,name=search,proto3" json:"search,omitempty"`      // 详细搜索
	Order    []*OrderParam  `protobuf:"bytes,4,rep,name=order,proto3" json:"order,omitempty"`        // 排序
}

func (x *PaginatorReq) Reset() {
	*x = PaginatorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginator_v1_paginator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatorReq) ProtoMessage() {}

func (x *PaginatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_v1_paginator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatorReq.ProtoReflect.Descriptor instead.
func (*PaginatorReq) Descriptor() ([]byte, []int) {
	return file_paginator_v1_paginator_proto_rawDescGZIP(), []int{2}
}

func (x *PaginatorReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatorReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginatorReq) GetSearch() []*SearchParam {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *PaginatorReq) GetOrder() []*OrderParam {
	if x != nil {
		return x.Order
	}
	return nil
}

// 分页响应
type PaginatorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         //第几页
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` //页大小
	Total    int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`       //总数
}

func (x *PaginatorReply) Reset() {
	*x = PaginatorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginator_v1_paginator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatorReply) ProtoMessage() {}

func (x *PaginatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_v1_paginator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatorReply.ProtoReflect.Descriptor instead.
func (*PaginatorReply) Descriptor() ([]byte, []int) {
	return file_paginator_v1_paginator_proto_rawDescGZIP(), []int{3}
}

func (x *PaginatorReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatorReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginatorReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_paginator_v1_paginator_proto protoreflect.FileDescriptor

var file_paginator_v1_paginator_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1d, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xba, 0x48, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x48, 0x0a, 0x03, 0x65,
	0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x36, 0xba, 0x48, 0x33, 0x72, 0x31, 0x52,
	0x01, 0x3d, 0x52, 0x02, 0x21, 0x3d, 0x52, 0x01, 0x3e, 0x52, 0x02, 0x3e, 0x3d, 0x52, 0x01, 0x3c,
	0x52, 0x02, 0x3c, 0x3d, 0x52, 0x02, 0x49, 0x4e, 0x52, 0x06, 0x4e, 0x4f, 0x54, 0x20, 0x49, 0x4e,
	0x52, 0x04, 0x4c, 0x49, 0x4b, 0x45, 0x52, 0x08, 0x4e, 0x4f, 0x54, 0x20, 0x4c, 0x49, 0x4b, 0x45,
	0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x24, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0e, 0xba, 0x48, 0x0b, 0x72, 0x09, 0x52, 0x03, 0x41, 0x4e, 0x44,
	0x52, 0x02, 0x4f, 0x52, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x22, 0x4f, 0x0a, 0x0a, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1d, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xba, 0x48, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x22, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10, 0xba, 0x48, 0x0d, 0x72, 0x0b, 0x52, 0x03, 0x41, 0x53,
	0x43, 0x52, 0x04, 0x44, 0x45, 0x53, 0x43, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0xb0, 0x01, 0x0a,
	0x0c, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xba, 0x48, 0x04,
	0x1a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0xba, 0x48,
	0x07, 0x1a, 0x05, 0x18, 0xe8, 0x07, 0x28, 0x01, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x2b, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22,
	0x56, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x75, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x0e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x10, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50,
	0x58, 0x58, 0xaa, 0x02, 0x09, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0xca, 0x02,
	0x09, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0xe2, 0x02, 0x15, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x09, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paginator_v1_paginator_proto_rawDescOnce sync.Once
	file_paginator_v1_paginator_proto_rawDescData = file_paginator_v1_paginator_proto_rawDesc
)

func file_paginator_v1_paginator_proto_rawDescGZIP() []byte {
	file_paginator_v1_paginator_proto_rawDescOnce.Do(func() {
		file_paginator_v1_paginator_proto_rawDescData = protoimpl.X.CompressGZIP(file_paginator_v1_paginator_proto_rawDescData)
	})
	return file_paginator_v1_paginator_proto_rawDescData
}

var file_paginator_v1_paginator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paginator_v1_paginator_proto_goTypes = []interface{}{
	(*SearchParam)(nil),    // 0: paginator.SearchParam
	(*OrderParam)(nil),     // 1: paginator.OrderParam
	(*PaginatorReq)(nil),   // 2: paginator.PaginatorReq
	(*PaginatorReply)(nil), // 3: paginator.PaginatorReply
}
var file_paginator_v1_paginator_proto_depIdxs = []int32{
	0, // 0: paginator.PaginatorReq.search:type_name -> paginator.SearchParam
	1, // 1: paginator.PaginatorReq.order:type_name -> paginator.OrderParam
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_paginator_v1_paginator_proto_init() }
func file_paginator_v1_paginator_proto_init() {
	if File_paginator_v1_paginator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paginator_v1_paginator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paginator_v1_paginator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paginator_v1_paginator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginatorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paginator_v1_paginator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginatorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paginator_v1_paginator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paginator_v1_paginator_proto_goTypes,
		DependencyIndexes: file_paginator_v1_paginator_proto_depIdxs,
		MessageInfos:      file_paginator_v1_paginator_proto_msgTypes,
	}.Build()
	File_paginator_v1_paginator_proto = out.File
	file_paginator_v1_paginator_proto_rawDesc = nil
	file_paginator_v1_paginator_proto_goTypes = nil
	file_paginator_v1_paginator_proto_depIdxs = nil
}
